# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
#
# $Id: pkgIndex.tcl,v 1.5 2003/08/05 01:12:45 cleverly Exp $
#

package ifneeded nstcl-core 1.2 [list source [file join $dir nstcl-core.tcl]]
package ifneeded nstcl-database 1.2 [list source [file join $dir nstcl-database.tcl]]
package ifneeded nstcl-database-devnull 1.2 [list source [file join $dir nstcl-database-devnull.tcl]]
package ifneeded nstcl-database-echo 1.2 [list source [file join $dir nstcl-database-echo.tcl]]
package ifneeded nstcl-database-odbc 1.2 [list source [file join $dir nstcl-database-odbc.tcl]]
package ifneeded nstcl-database-oracle 1.2 [list source [file join $dir nstcl-database-oracle.tcl]]
package ifneeded nstcl-database-postgres 1.2 [list source [file join $dir nstcl-database-postgres.tcl]]
package ifneeded nstcl-database-solid 1.2 [list source [file join $dir nstcl-database-solid.tcl]]
package ifneeded nstcl-database-sqlite 1.2 [list source [file join $dir nstcl-database-sqlite.tcl]]
package ifneeded nstcl-database-mysql 1.2 [list source [file join $dir nstcl-database-mysql.tcl]]
package ifneeded nstcl-database-sybase 1.2 [list source [file join $dir nstcl-database-sybase.tcl]]
package ifneeded nstcl-fwdcompat 1.2 [list source [file join $dir nstcl-fwdcompat.tcl]]
package ifneeded nstcl-html 1.2 [list source [file join $dir nstcl-html.tcl]]
package ifneeded nstcl-http 1.2 [list source [file join $dir nstcl-http.tcl]]
package ifneeded nstcl-images 1.2 [list source [file join $dir nstcl-images.tcl]]
package ifneeded nstcl-log 1.2 [list source [file join $dir nstcl-log.tcl]]
package ifneeded nstcl-misc 1.2 [list source [file join $dir nstcl-misc.tcl]]
package ifneeded nstcl-nssets 1.2 [list source [file join $dir nstcl-nssets.tcl]]
package ifneeded nstcl-sendmail 1.2 [list source [file join $dir nstcl-sendmail.tcl]]
package ifneeded nstcl-templating 1.2 [list source [file join $dir nstcl-templating.tcl]]
package ifneeded nstcl-time 1.2 [list source [file join $dir nstcl-time.tcl]]
package ifneeded nstcl 0.999 [list source [file join $dir nstcl-ver0-compat.tcl]]
package ifneeded nstcl-all 1.2 [list source [file join $dir nstcl.tcl]]
package ifneeded nstcl 1.2   [list source [file join $dir nstcl.tcl]]
